
version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres_db
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_USER: restaurant_review
      POSTGRES_DB: restaurant_review
      POSTGRES_PASSWORD: restaurant_review
    ports:
      - "3310:5432"
    expose:
      - "5432"
    networks:
      - restaurant-review-postgres-network

  mailhog: # Tests Emails
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # Port SMTP
      - "8025:8025"  # Interface Web
    networks:
      - restaurant-review-postgres-network

  app:
    build: .
    restart: always
    container_name: spring_boot_app
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: restaurant_review
      DB_USER: restaurant_review
      DB_PASSWORD: restaurant_review
    ports:
      - "9090:9090"
    depends_on:
      - db
    networks:
      - restaurant-review-postgres-network

networks:
  restaurant-review-postgres-network:
    driver: bridge
