server:
  port: 9090
  servlet:
    context-path: /api

spring:
  application:
    name: Restaurant Review
  datasource:
    url: jdbc:${DB_SGDB}://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  paths-to-match: /**
  paths-to-exclude: /swagger-resources/**
  swagger-ui:
    use-root-path: true

spring.data.web:
  pageable:
    size-parameter: pageSize
    page-parameter: pageNumber
    default-page-size: 15
    one-indexed-parameters: true
    max-page-size: 1000
  sort:
    sort-parameter: order
