name: Run Test Api

on: [pull_request, push]

jobs:
  tests:
    name: Installing Packages and Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run Test with Coverage
        run: mvn test jacoco:report --file pom.xml

      - name: Show Coverage Percentage
        run: |
          echo "Coverage Summary:"
          grep -A 1 "Total" target/site/jacoco/index.html | tail -n 1
