name: Run Test Api

on: [pull_request, push]

jobs:
  tests:
    name: Installing Packages and Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven

      - name: Run Test
        run: mvn -B test -DskipTests=false --file pom.xml